name: ubunu

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        #!/bin/bash

        adduser yusuf
        usermod -aG sudo yusuf
        echo 'yusuf ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/custom && chmod 0440 /etc/sudoers.d/custom