name: ubunu

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        sudo apt install xfce4 2>/dev/null
        wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb -P /tmp
        sudo apt install /tmp/chrome-remote-desktop_current_amd64.deb
        DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="4/0AfJohXm0wmfRvzJx_f9PBtIuR0BVmAhBAF4Qvwg3mv-er4Xy4lRku9wa9HsCPIDx3AawIw" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname)
        sudo apt install blender