name: ubunu

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        sudo apt install xfce4
        sudo apt install blender