name: ubunu

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        sudo apt install xfce4 2>/dev/null
        wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb -P /tmp
        sudo apt install /tmp/chrome-remote-desktop_current_amd64.deb
    - name: crd
      run: | 
        ${{ inputs.authcode }}--pin=123456
        sudo apt install blender