# This is a basic workflow to help you get started with Actions

name: Windows-10

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      win_version:
        type: choice
        options:
        - windows-2022
        - windows-2019
   
jobs:
  build:
    runs-on: ${{ inputs.win_version }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Initializing Setup
      run: ./setup.ps1
    - name: starting rdp
      run: ${{ github.event.inputs.authcode }} -pin=654321
    - name: Keep Alive
      run: ./tc.ps1


    
