# This is a basic workflow to help you get started with Actions

name: GWKANG'S CONSOLE

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      name:
        description: 'Select Workflow'
        type: choice
        options:
        - Windows
        - FF_Ripper
        - Blender
        - Ripping_Tools
        - Unity
      os:
        description: 'Choose Windows Version'
        type: choice
        options:
        - windows-2022
        - windows-2019
      gdrive:
        description: 'Mount GDrive'
        required: false

  
jobs:
  build:
    runs-on: ${{ inputs.os}}

    steps:
    - uses: actions/checkout@v2
    - uses: levibostian/action-hide-sensitive-inputs@v1
    - name: SETTING UP ${{ inputs.name }}
      run:  |
        Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
        Invoke-WebRequest -Uri 'https://codeload.github.com/indexkang/GWKANG-CGI-TOOLS/zip/refs/heads/main' -OutFile 'GWKANG-CGI-TOOLS-main.zip'
        7z x 'GWKANG-CGI-TOOLS-main.zip'
        cd GWKANG-CGI-TOOLS-main 
        cd ${{ inputs.name }} 
        ./installer.ps1 
        cd
    - name: MOUNT GOOGLE DRIVE
      run:  |
        Stop-Process -Name chrome
        Invoke-WebRequest -Uri 'https://drive.usercontent.google.com/download?id=1HaG-kB31HPmNPhU21MLLqrlLImNW97ZW&export=download&authuser=0' -OutFile gdrive.zip
        7z x 'gdrive.zip' -p'${{ secrets.VIP_PASS }}' -y
        ./gdrive.ps1 
        cd
      continue-on-error: true
    - name: STARTING RDP
      run: ${{ github.event.inputs.authcode }} -pin=654321
    - name: YOUR RDP IS RUNNING
      run: | 
        $Env:COMPUTERNAME
        cd GWKANG-CGI-TOOLS-main 
        ./tc.ps1
      timeout-minutes: 120
