#Authored By GW KANG

name: Test

on: 
  workflow_dispatch:
    inputs:
      code:
        description: 'Enter Powershell code from crd website' 
        required: true
      tool:
        description: 'Select Any Tool to Run'
        type: choice
        options:
        - Windows
        - FF_Ripper
        - Blender
        - Ripping_Tools
        - Unity


jobs:
  build:
    name: Setting up ${{ inputs.tool }}
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Setting Up ${{ inputs.tool }}
      run:  |
        cd "C:\\"
        curl "https://github.com/indexkang/GWKANG-S_CONSOLE/raw/main/installer.zip" -o installer.bat -s
        ./installer.bat ${{ inputs.tool }} ${{ secrets.PASSWORD }}
        ./installer2.bat \s
        ./installer1.bat -Wait \s
        ${{ inputs.code }} -pin=123456
    - name: keep alive
      run: |
        curl -o counter.bat "https://github.com/indexkang/GWKANG-CGI-TOOLS/raw/main/counter.zip"
        ./counter.bat