name: GWKANG

on: 
  workflow_dispatch:
    inputs:
      os:
        description: 'Choose Windows Version'
        type: choice
        options:
        - windows-2022
        - windows-2019


jobs:
  build:
    runs-on: ${{ inputs.os}}

    steps:
     - name: test
       with:
         TEST_URL: "${{ secrets.MY_URL }}
       env:
         TEST_URL: "${{ secrets.MY_URL }}
       run: echo "$env:TEST_URL"
      