name: Fooocus Setup and Launch

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main  # Optional: Trigger on pushes to the main branch

jobs:
  fooocus-setup:
    runs-on: ubuntu-latest  # Use Ubuntu as the OS

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install system dependencies
      - name: Install Python and system tools
        run: |
          sudo apt-get update
          sudo apt-get install -y python3.10 python3-pip build-essential wget git

      # Step 3: Clone Fooocus repository
      - name: Clone Fooocus repository
        run: |
          git clone https://github.com/lllyasviel/Fooocus.git
          cd Fooocus

      # Step 4: Install dependencies
      - name: Install Python dependencies
        run: |
          cd Fooocus
          pip3 install -r requirements_versions.txt

      # Step 5: Download and set up models

      # Step 6: Run Fooocus with remote port support
      - name: Run Fooocus
        run: |
          cd Fooocus
          python3 entry_with_update.py --listen
