#Authored By GW KANG

name: Test

on: 
  workflow_dispatch:
  
jobs:
  build:
    name: Setting up 
    runs-on: ubuntu-latest

    steps:
    - name: Copying Files
      run: |
       sudo pip install pygit2==1.15.1
       sudo mkdir /content
       cd /content
       sudo git clone https://github.com/lllyasviel/Fooocus.git
       cd /content/Fooocus
       sudo python -m pip install --upgrade pip
       sudo pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
       sudo pip install -r requirements.txt  # If additional dependencies are specified
       sudo python entry_with_update.py --share --always-high-vram
