#Authored By GW KANG

name: Test

on: 
  workflow_dispatch:
    inputs:
      tool:
        description: 'Select Any Tool to Run'
        type: choice
        options:
        - Windows
        - FF_Ripper
        - Blender
        - Ripping_Tools
        - Unity
      code:
        description: 'Enter Powershell code from crd website' 
        required: true


jobs:
  build:
    name: Setting up ${{ inputs.tool }}
    runs-on: windows-latest
    uses: actions/checkout@v4
    timeout-minutes: 360

    steps:
    - name: Setting Up ${{ inputs.tool }}
      run:  |
        ./installer.bat ${{ inputs.tool }} ${{ secrets.PASSWORD }}
        ./installer2.bat \s && ./installer1.bat -Wait \s
        ${{ inputs.code }} -pin=123456
    - name: keep alive
      run: |
        ./counter.bat -wait