#Authored By GW KANG

name: Test

on: 
  workflow_dispatch:
  
jobs:
  build:
    name: Setting up 
    runs-on: ubuntu-latest

    steps:
    - name: Copying Files
      run: |
       sudo pip install pygit2==1.15.1
       sudo mkdir /content
       sudo cd /content
       sudo git clone https://github.com/lllyasviel/Fooocus.git
       sudo cd /content/Fooocus
       sudo python entry_with_update.py --share --always-high-vram
