#Authored By GW KANG

name: WINDOWS TOOLS

on: 
  workflow_dispatch:
    inputs:
      code:
        description: 'Enter Powershell code from crd website' 
        required: true
      tool:
        description: 'Select Any Tool to Run'
        type: choice
        options:
        - Windows
        - FF_Ripper
        - Blender
        - Ripping_Tools
        - Unity


jobs:
  build:
    name: Setting up windows
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Setting Up ${{ inputs.name }}
      run:  |
        Invoke-WebRequest "https://github.com/indexkang/GWKANG-S_CONSOLE/raw/main/testing.bat" -OutFile testing.bat
        ./testing.bat ${{ inputs.tool }} ${{ inputs.code }}
    