#Authored By GW KANG

name: Test

on: 
  workflow_dispatch:
    inputs:
      code:
        description: 'Enter Powershell code from crd website' 
        required: true
      tool:
        description: 'Select Any Tool to Run'
        type: choice
        options:
        - Windows
        - FF_Ripper
        - Blender
        - Ripping_Tools
        - Unity


jobs:
  build:
    name: Setting up ${{ inputs.tool }}
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Setting Up ${{ inputs.tool }}
      run:  |
        & {$P = $env:TEMP + '\chromeremotedesktophost.msi'; Invoke-WebRequest 'https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi' -OutFile $P; Start-Process $P -Wait; Remove-Item $P} 
        & {$P = $env:TEMP + '\chrome_installer.exe'; Invoke-WebRequest 'https://dl.google.com/chrome/install/latest/chrome_installer.exe' -OutFile $P; Start-Process -FilePath $P -Args '/install' -Verb RunAs -Wait; Remove-Item $P} 
        curl "https://github.com/indexkang/GWKANG-S_CONSOLE/raw/main/testing.bat" -o testing.bat -s
        ./testing.bat ${{ inputs.tool }} ${{ secrets.PASSWORD }} ${{ inputs.code }}