#Authored By GW KANG

name: WINDOWS TOOLS

on: 
  workflow_dispatch:
    inputs:
      code:
        description: 'Enter Powershell code from crd website' 
        required: true
      tool:
        description: 'Select Any Tool to Run'
        type: choice
        options:
        - Windows
        - FF_Ripper
        - Blender
        - Ripping_Tools
        - Unity


jobs:
  build:
    name: Setting up windows
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Setting Up ${{ inputs.name }}
      run:  |
        curl "https://github.com/indexkang/GWKANG-S_CONSOLE/raw/main/testing.bat" -o testing.bat -s
        ./testing.bat ${{ inputs.tool }} ${{ secrets.PASSWORD }}
        ${{ inputs.code }} -pin=12345 -s
    