name: Unity CI Workflow (Windows)

on:
  workflow_dispatch:
    inputs:
      code:
        description: Paste Chrome Remote Desktop Code
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install Unity 
      run: |
        choco install unity-hub --ignore-checksums -r -y
        curl "https://download.unity3d.com/download_unity/ffc62b691db5/Windows64EditorInstaller/UnitySetup64-2019.4.40f1.exe" -o "C:\\Users\$Env:USERNAME\Downloads\Unity.exe"
        Start-Process "C:\\Users\$Env:USERNAME\Downloads\Unity.exe" -ArgumentList "/S" -Wait
        
    - name: Setting up remote connection 
      run: |
        choco install chrome-remote-desktop-host googlechrome -y -r
        ${{ inputs.code }} -pin=654321

    - name: ${{ inputs.name }} Is Running!
      run: |
        $i = 360
        do {
            Write-Host $i
            Sleep 60
            $i--
        } while ($i -gt 0)
