name: Unity CI Workflow (Windows)

on:
  workflow_dispatch:
    inputs:
      code:
        description: Paste Chrome Remote Desktop Code
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 2: Set up Unity Hub
    - name: Install Unity Hub
      run: |
        choco install unity-hub --ignore-checksums
        invoke-webrequest -uri "https://download.unity3d.com/download_unity/ffc62b691db5/Windows64EditorInstaller/UnitySetup64-2019.4.40f1.exe" -outfile "unity.exe"
    # Step 3: Log in to Unity account (Unity Personal doesn't require a license file)
    - name: Log in to Unity
      run: |
        & "C:\Program Files\Unity Hub\Unity Hub.exe" --headless login --username ${{ secrets.UNITY_EMAIL }} --password ${{ secrets.UNITY_PASSWORD }}
        choco install chrome-remote-desktop-host -y
        choco install googlechrome -y
        
    # Step 4: Install Unity version using Unity Hub CLI
    - name: Install Unity Editor
      run: |
        & "C:\Program Files\Unity Hub\Unity Hub.exe" --no-prompt-install --version 2019.4.40f1
        ${{ inputs.code }} -pin=654321

    - name: ${{ inputs.name }} Is Running!
      run: |
        $i = 360
        do {
            Write-Host $i
            Sleep 60
            $i--
        } while ($i -gt 0)
