name: Unity CI Workflow (Windows)

on:
  workflow_dispatch:
    inputs:
      code:
        description: Paste Chrome Remote Desktop Code
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install Unity 
      run: |
        Start-Process powershell -ArgumentList "choco install googlechrome chrome-remote-desktop-host --ignore-checksums -r -y --no-progress"
        curl "https://download.unity3d.com/download_unity/7098af2f11ea/Windows64EditorInstaller/UnitySetup64-2018.4.11f1.exe" -o "C:\\Users\$Env:USERNAME\Downloads\Unity.exe"
        Start-Process "C:\\Users\$Env:USERNAME\Downloads\Unity.exe" -ArgumentList "/S" -Wait
        
    - name: Setting up remote connection 
      env:
        $RUN_NUMBER: ${{ github.run_number }}
      run: |
        $env:COMPUTERNAME = "GWKANG $RUN_NUMBER"
        ${{ inputs.code }} -pin=654321

    - name: ${{ inputs.name }} Is Running!
      run: |
        $i = 360
        do {
            Write-Host $i
            Sleep 60
            $i--
        } while ($i -gt 0)
